# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'result_upstream.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont


class Ui_Upstream_Screen_Result(object):

    def setupUi(self, Upstream_Screenresult):
        Upstream_Screenresult.setWindowIcon(QtGui.QIcon("unnamed.png"))
        Upstream_Screenresult.setObjectName("Upstream_Screen")
        Upstream_Screenresult.resize(691, 492)       ### size
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)  ### size
        sizePolicy.setHorizontalStretch(0)### size
        sizePolicy.setVerticalStretch(0)   ### size
        sizePolicy.setHeightForWidth(Upstream_Screenresult.sizePolicy().hasHeightForWidth())   ###
        Upstream_Screenresult.setSizePolicy(sizePolicy)
        Upstream_Screenresult.setMinimumSize(QtCore.QSize(691, 492))
        Upstream_Screenresult.setMaximumSize(QtCore.QSize(691, 492))
        self.Background_label = QtWidgets.QLabel(Upstream_Screenresult)
        self.Background_label.setGeometry(QtCore.QRect(0, 0, 691, 492))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Background_label.sizePolicy().hasHeightForWidth())
        self.Background_label.setSizePolicy(sizePolicy)
        self.Background_label.setMinimumSize(QtCore.QSize(691, 492))
        self.Background_label.setMaximumSize(QtCore.QSize(691, 492))
        self.Background_label.setText("")
        self.Background_label.setPixmap(QtGui.QPixmap("pic3.jpg"))
        self.Background_label.setScaledContents(True)        #####
        self.Background_label.setWordWrap(True)               #######
        self.Background_label.setObjectName("Background_label")
        self.Topic_label = QtWidgets.QLabel(Upstream_Screenresult)
        self.Topic_label.setGeometry(QtCore.QRect(100, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)             #########
        font.setBold(True)
        font.setWeight(75)               ##########
        self.Topic_label.setFont(font)    ##### size bhi de skte the
        self.Topic_label.setObjectName("Topic_label")       #######
        self.input_label1 = QtWidgets.QLabel(Upstream_Screenresult)
        self.input_label1.setGeometry(QtCore.QRect(335, 108, 101, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label1.setFont(font)
        self.input_label1.setObjectName("input_label1")
        self.input_label2 = QtWidgets.QLabel(Upstream_Screenresult)
        self.input_label2.setGeometry(QtCore.QRect(260, 140, 171, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label2.setFont(font)
        self.input_label2.setObjectName("input_label2")
        self.input_label5 = QtWidgets.QLabel(Upstream_Screenresult)
        self.input_label5.setGeometry(QtCore.QRect(76, 207, 361, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label5.setFont(font)
        self.input_label5.setObjectName("input_label5")
        self.input_label4 = QtWidgets.QLabel(Upstream_Screenresult)
        self.input_label4.setGeometry(QtCore.QRect(326, 240, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label4.setFont(font)
        self.input_label4.setObjectName("input_label4")
        self.input_label6 = QtWidgets.QLabel(Upstream_Screenresult)
        self.input_label6.setGeometry(QtCore.QRect(75, 290, 361, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label6.setFont(font)
        self.input_label6.setObjectName("input_label6")
        self.input_label7 = QtWidgets.QLabel(Upstream_Screenresult)
        self.input_label7.setGeometry(QtCore.QRect(36, 323, 391, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label7.setFont(font)
        self.input_label7.setObjectName("input_label7")
        self.input_label3 = QtWidgets.QLabel(Upstream_Screenresult)
        self.input_label3.setGeometry(QtCore.QRect(38, 178, 401, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label3.setFont(font)
        self.input_label3.setObjectName("input_label3")
        self.input_label8 = QtWidgets.QLabel(Upstream_Screenresult)
        self.input_label8.setGeometry(QtCore.QRect(209, 375, 221, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label8.setFont(font)
        self.input_label8.setObjectName("input_label8")
        self.lineEdit_1 = QtWidgets.QLabel(Upstream_Screenresult)
        self.lineEdit_1.setGeometry(QtCore.QRect(450, 113, 165, 25))
        self.lineEdit_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        #self.lineEdit_1.setInputMask("")          ######
        #self.lineEdit_1.setFrame(True)           ######
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_1.setStyleSheet("background-color: white")
        self.lineEdit_2 = QtWidgets.QLabel(Upstream_Screenresult)
        self.lineEdit_2.setGeometry(QtCore.QRect(450, 145, 165, 25))
        self.lineEdit_2.setStyleSheet("background-color: white")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLabel(Upstream_Screenresult)
        self.lineEdit_3.setGeometry(QtCore.QRect(450, 179, 165, 25))
        self.lineEdit_3.setStyleSheet("background-color: white")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLabel(Upstream_Screenresult)
        self.lineEdit_4.setGeometry(QtCore.QRect(450, 211, 165, 25))
        self.lineEdit_4.setStyleSheet("background-color: white")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLabel(Upstream_Screenresult)
        self.lineEdit_5.setGeometry(QtCore.QRect(450, 295, 165, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setStyleSheet("background-color: white")
        self.lineEdit_6 = QtWidgets.QLabel(Upstream_Screenresult)
        self.lineEdit_6.setGeometry(QtCore.QRect(450, 243, 165, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.setStyleSheet("background-color: white")
        self.lineEdit_8 = QtWidgets.QLabel(Upstream_Screenresult)
        self.lineEdit_8.setGeometry(QtCore.QRect(450, 379, 165, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_8.setStyleSheet("background-color: white")
        self.lineEdit_7 = QtWidgets.QLabel(Upstream_Screenresult)
        self.lineEdit_7.setGeometry(QtCore.QRect(450, 326, 165, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_7.setStyleSheet("background-color: white")
        self.retranslateUi(Upstream_Screenresult)
        QtCore.QMetaObject.connectSlotsByName(Upstream_Screenresult)             ########

    def retranslateUi(self, Upstream_Screenresult):
        _translate = QtCore.QCoreApplication.translate             #######
        Upstream_Screenresult.setWindowTitle(_translate("Upstream_Screen", "Choke Pressure Estimator - Upstream Results"))
        self.Topic_label.setText(_translate("Upstream_Screen", "Results for Upstream Pressure Calculation"))
        self.input_label1.setText(_translate("Upstream_Screen", "Choke Area :"))
        self.input_label2.setText(_translate("Upstream_Screen", "Critical Pressure Ratio :"))
        self.input_label5.setText(_translate("Upstream_Screen", "Flow Rate at the minimum sonic flow condition :"))
        self.input_label4.setText(_translate("Upstream_Screen", "Flow Regime :"))
        self.input_label6.setText(_translate("Upstream_Screen", "Uptream Pressure given by sonic flow equation :"))
        self.input_label7.setText(_translate("Upstream_Screen", "Upstream Pressure given by sub-sonic flow equation :"))
        self.input_label3.setText(_translate("Upstream_Screen", "Minimum upstream pressure required for sonic flow :"))
        self.input_label8.setText(_translate("Upstream_Screen", "Estimated Upstream Pressure :"))
        self.lineEdit_2.setFont(QFont("Times New Roman",12,weight=QFont.Bold))
        self.lineEdit_1.setFont(QFont("Times New Roman",12,weight=QFont.Bold))
        self.lineEdit_3.setFont(QFont("Times New Roman", 12, weight=QFont.Bold))
        self.lineEdit_4.setFont(QFont("Times New Roman", 12, weight=QFont.Bold))
        self.lineEdit_5.setFont(QFont("Times New Roman", 12, weight=QFont.Bold))
        self.lineEdit_8.setFont(QFont("Times New Roman", 12, weight=QFont.Bold))
        self.lineEdit_6.setFont(QFont("Times New Roman", 12, weight=QFont.Bold))
        self.lineEdit_7.setFont(QFont("Times New Roman", 12, weight=QFont.Bold))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Upstream_Screenresult = QtWidgets.QWidget()    #####
    ui = Ui_Upstream_Screen_Result()
    ui.setupUi(Upstream_Screenresult)     ########
    Upstream_Screenresult.show()
    sys.exit(app.exec_())
