# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upstream.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCursor
from mresult_upstream import Ui_Upstream_Screen_Result
from math import sqrt
from decimal import Decimal
from scipy.optimize import fsolve


class Ui_Upstream_Screen(object):

    def _screen13(self):
        self.screen11 = QtWidgets.QMainWindow()
        self.up = Ui_Upstream_Screen_Result()
        self.up.setupUi(self.screen11)
        C7 = float(self.lineEdit_1.text())  # Downstream pressure (Pdn)
        C8 = float(self.lineEdit_2.text())  # Choke Size
        C9 = float(self.lineEdit_3.text())  # Flowline ID
        C10 = float(self.lineEdit_4.text())  # Gas Production rate (MSCF/Day)
        C12 = float(self.lineEdit_5.text())  # Gas Specific Heat Ratio (k)
        C11 = float(self.lineEdit_6.text())  # Gas Specific Gravity (gamma)
        C14 = float(self.lineEdit_7.text())  # Choke Discharge Coefficient
        C13 = float(self.lineEdit_8.text())  # Upstream temperature

        # Choke Size
        C18 = (3.14 / 4) * (C8 / 64) ** 2

        # Critical Pressure Ratio
        C19 = (2 / (C12 + 1)) ** (C12 / (C12 - 1))

        # Minimum upstream pressure required for sonic flow
        C20 = C7 / C19

        # Flow rate at the minimum sonic flow condition
        C21 = 879.0 * C14 * C18 * C20 * sqrt(C12 / C11 / (C13 + 460) * (2 / (C12 + 1)) ** ((C12 + 1) / (C12 - 1)))

        # Flow regime (1=sonic flow; -1=subsonic flow)
        C22 = (C10 - C21) / abs(C10 - C21)  # Ye line chutiyapa hai

        if C10 < C21:
            flowtype = ' Subsonic Flow'
        else:
            flowtype = ' Sonic Flow'

        # Upstream pressure given by sonic flow equation
        C24 = C10 / (879 * C14 * C18 * sqrt((C12 / C11 / (C13 + 460)) * (2 / (C12 + 1)) ** ((C12 + 1) / (C12 - 1))))

        # Upstream pressure given by subsonic flow equation

        # C25=C21/(1248.0*C14*C18*sqrt((C12/((C12-1)*C11*(C13+460)))*((C7/C20)**(2.0/C12)-(C7/C20)**((C12+1.0)/C12))))    # Idhar kuch ghapla hai
        def f(x):
            return (1248.0 * C14 * x * C18 * sqrt((C12 / ((C12 - 1) * C11 * (C13 + 460))) * (
                        (C7 / x) ** (2.0 / C12) - (C7 / x) ** ((C12 + 1.0) / C12)))) - C10

        ans1 = fsolve(lambda x: f(x), C24)
        C25 = ans1[0]

        # Estimated upstream pressure
        if flowtype == ' Subsonic Flow':
            C26 = C25
        else:
            C26 = C24

        self.up.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.up.lineEdit_1.setText(str(round(Decimal(C18), 5)) + ' sq. inches')
        self.up.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.up.lineEdit_2.setText(str(round(Decimal(C19), 8)))
        self.up.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.up.lineEdit_3.setText(str(round(Decimal(C20), 3)) + ' psia')
        self.up.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.up.lineEdit_4.setText(str(round(Decimal(C21), 3)) + ' Mscf/day')
        self.up.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.up.lineEdit_6.setText(str(flowtype))
        self.up.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.up.lineEdit_5.setText(str(round(Decimal(C24), 3)) + ' psia')
        self.up.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.up.lineEdit_7.setText(str(round(Decimal(C25), 3)) + ' psia')
        self.up.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.up.lineEdit_8.setText(str(round(Decimal(C26), 3)) + ' psia')

        self.screen11.show()

    def setupUi(self, Upstream_Screen):

        Upstream_Screen.setWindowIcon(QtGui.QIcon("unnamed.png"))
        Upstream_Screen.setObjectName("Upstream_Screen")
        Upstream_Screen.resize(691, 492)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Upstream_Screen.sizePolicy().hasHeightForWidth())
        Upstream_Screen.setSizePolicy(sizePolicy)
        Upstream_Screen.setMinimumSize(QtCore.QSize(691, 492))
        Upstream_Screen.setMaximumSize(QtCore.QSize(691, 492))
        self.Background_label = QtWidgets.QLabel(Upstream_Screen)
        self.Background_label.setGeometry(QtCore.QRect(0, 0, 691, 492))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Background_label.sizePolicy().hasHeightForWidth())
        self.Background_label.setSizePolicy(sizePolicy)
        self.Background_label.setMinimumSize(QtCore.QSize(691, 492))
        self.Background_label.setMaximumSize(QtCore.QSize(691, 492))
        self.Background_label.setText("")
        self.Background_label.setPixmap(QtGui.QPixmap("u1.jpg"))
        self.Background_label.setScaledContents(True)
        self.Background_label.setWordWrap(True)
        self.Background_label.setObjectName("Background_label")
        self.Topic_label = QtWidgets.QLabel(Upstream_Screen)
        self.Topic_label.setGeometry(QtCore.QRect(10, -10, 681, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.Topic_label.setFont(font)
        self.Topic_label.setObjectName("Topic_label")
        self.input_label1 = QtWidgets.QLabel(Upstream_Screen)
        self.input_label1.setGeometry(QtCore.QRect(65, 100, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label1.setFont(font)
        self.input_label1.setObjectName("input_label1")
        self.input_label2 = QtWidgets.QLabel(Upstream_Screen)
        self.input_label2.setGeometry(QtCore.QRect(75, 133, 201, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label2.setFont(font)
        self.input_label2.setObjectName("input_label2")
        self.input_label5 = QtWidgets.QLabel(Upstream_Screen)
        self.input_label5.setGeometry(QtCore.QRect(25, 199, 251, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label5.setFont(font)
        self.input_label5.setObjectName("input_label5")
        self.input_label4 = QtWidgets.QLabel(Upstream_Screen)
        self.input_label4.setGeometry(QtCore.QRect(35, 232, 241, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label4.setFont(font)
        self.input_label4.setObjectName("input_label4")
        self.input_label6 = QtWidgets.QLabel(Upstream_Screen)
        self.input_label6.setGeometry(QtCore.QRect(85, 265, 191, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label6.setFont(font)
        self.input_label6.setObjectName("input_label6")
        self.input_label7 = QtWidgets.QLabel(Upstream_Screen)
        self.input_label7.setGeometry(QtCore.QRect(65, 298, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label7.setFont(font)
        self.input_label7.setObjectName("input_label7")
        self.input_label3 = QtWidgets.QLabel(Upstream_Screen)
        self.input_label3.setGeometry(QtCore.QRect(105, 166, 171, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label3.setFont(font)
        self.input_label3.setObjectName("input_label3")
        self.input_label8 = QtWidgets.QLabel(Upstream_Screen)
        self.input_label8.setGeometry(QtCore.QRect(45, 331, 231, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_label8.setFont(font)
        self.input_label8.setObjectName("input_label8")
        self.lineEdit_1 = QtWidgets.QLineEdit(Upstream_Screen)
        self.lineEdit_1.setGeometry(QtCore.QRect(285, 105, 150, 25))
        self.lineEdit_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_1.setInputMask("")
        self.lineEdit_1.setText("")
        self.lineEdit_1.setFrame(True)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_1.returnPressed.connect(self._screen13)
        self.lineEdit_2 = QtWidgets.QLineEdit(Upstream_Screen)
        self.lineEdit_2.setGeometry(QtCore.QRect(285, 138, 150, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.returnPressed.connect(self._screen13)
        self.lineEdit_3 = QtWidgets.QLineEdit(Upstream_Screen)
        self.lineEdit_3.setGeometry(QtCore.QRect(285, 170, 150, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.returnPressed.connect(self._screen13)
        self.lineEdit_4 = QtWidgets.QLineEdit(Upstream_Screen)
        self.lineEdit_4.setGeometry(QtCore.QRect(285, 202, 150, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.returnPressed.connect(self._screen13)
        self.lineEdit_6 = QtWidgets.QLineEdit(Upstream_Screen)
        self.lineEdit_6.setGeometry(QtCore.QRect(285, 234, 150, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.returnPressed.connect(self._screen13)
        self.lineEdit_5 = QtWidgets.QLineEdit(Upstream_Screen)
        self.lineEdit_5.setGeometry(QtCore.QRect(285, 268, 150, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.returnPressed.connect(self._screen13)
        self.lineEdit_8 = QtWidgets.QLineEdit(Upstream_Screen)
        self.lineEdit_8.setGeometry(QtCore.QRect(285, 301, 150, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_8.returnPressed.connect(self._screen13)
        self.lineEdit_7 = QtWidgets.QLineEdit(Upstream_Screen)
        self.lineEdit_7.setGeometry(QtCore.QRect(285, 335, 150, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_7.returnPressed.connect(self._screen13)
        self.calc_Button = QtWidgets.QPushButton(Upstream_Screen)
        self.calc_Button.setGeometry(QtCore.QRect(505, 210, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.calc_Button.setFont(font)
        self.calc_Button.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.calc_Button.setObjectName("calc_Button")
        self.calc_Button.clicked.connect(self._screen13)

        self.retranslateUi(Upstream_Screen)
        QtCore.QMetaObject.connectSlotsByName(Upstream_Screen)

    def retranslateUi(self, Upstream_Screen):
        _translate = QtCore.QCoreApplication.translate
        Upstream_Screen.setWindowTitle(_translate("Upstream_Screen", "Choke Pressure Estimator - Upstream"))
        self.Topic_label.setText(_translate("Upstream_Screen", "Calculating Upstream Pressure at choke for dry gases"))
        self.input_label1.setText(_translate("Upstream_Screen", "Downstream Pressure (psi) :"))
        self.input_label2.setText(_translate("Upstream_Screen", "  Choke Size (1/64 inches) :"))
        self.input_label5.setText(_translate("Upstream_Screen", " Gas Production Rate (Mscf/day) :"))
        self.input_label4.setText(_translate("Upstream_Screen", "  Gas Specific Gravity (1 for air) :"))
        self.input_label6.setText(_translate("Upstream_Screen", " Gas Specific Heat Ratio :"))
        self.input_label7.setText(_translate("Upstream_Screen", "Upstream Temperature (°F) :"))
        self.input_label3.setText(_translate("Upstream_Screen", "  Flowline ID (inches) :"))
        self.input_label8.setText(_translate("Upstream_Screen", "  Choke Discharge Coefficient :"))
        self.lineEdit_1.setPlaceholderText(_translate("Upstream_Screen", "                Enter value"))
        self.lineEdit_2.setPlaceholderText(_translate("Upstream_Screen", "                Enter value"))
        self.lineEdit_3.setPlaceholderText(_translate("Upstream_Screen", "                Enter value"))
        self.lineEdit_4.setPlaceholderText(_translate("Upstream_Screen", "                Enter value"))
        self.lineEdit_6.setPlaceholderText(_translate("Upstream_Screen", "                Enter value"))
        self.lineEdit_5.setPlaceholderText(_translate("Upstream_Screen", "                Enter value"))
        self.lineEdit_8.setPlaceholderText(_translate("Upstream_Screen", "                Enter value"))
        self.lineEdit_7.setPlaceholderText(_translate("Upstream_Screen", "                Enter value"))
        self.calc_Button.setText(_translate("Upstream_Screen", "Calculate!"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Upstream_Screen = QtWidgets.QWidget()
    ui = Ui_Upstream_Screen()
    ui.setupUi(Upstream_Screen)
    Upstream_Screen.show()
    sys.exit(app.exec_())